### ISSUE TITLE
发送组消息方法返回true，但消息没发送进组里

### ISSUE THREAD

**Issue by helloqhq** [slince/smartqq#10]
$message = new GroupMessage($group, new Content('哈喽'));
$result = $smartQQ->sendMessage($message);
var_dump($result);

**Comment by slince** [comment]
好友消息与讨论组消息正常吗

**Comment by slince** [comment]
已修复 更新到2.0.5即可

**Comment by helloqhq** [comment]
好友消息也发送失败
Send Error

**Comment by slince** [comment]
用2.0.5版本试一下；如果还有问题先去w.qq.com 试一下能否正常收发消息；我调试的已经没有问题了
