### ISSUE TITLE
FriendMessage not working

### ISSUE THREAD

**Issue by artsemi** [slince/smartqq#14]
Hi! This is my code: 

```
$friends = $smartQQ->getFriends();
$friend = $friends->firstByAttribute('nick', 'Artem');

print_r($friend);

$message = new \Slince\SmartQQ\Message\Request\FriendMessage($friend, new \Slince\SmartQQ\Message\Content('Test message'));
$result = $smartQQ->sendMessage($message);

var_dump($result);
```

My results:
$friend - 
```
Slince\SmartQQ\Entity\Friend Object
(
    [flag:protected] => 293601280
    [face:protected] => 0
    [nick:protected] => Artem
    [qq:protected] => 
    [isVip:protected] => 
    [vipLevel:protected] => 0
    [category:protected] => Slince\SmartQQ\Entity\Category Object
        (
            [name:protected] => 我的好友
            [index:protected] => 0
            [sort:protected] => 0
        )

    [markName:protected] => KarArt
    [uin:protected] => 3023354877
)
```

$result - `bool(false)`

Why I get false in $result? Thanks!

**Comment by artsemi** [comment]
```
    [errmsg] => error!!!
    [retcode] => 103
```
This is my $jsonData from Response.
What I should do? I go to w.qq.com, but I don't understand - What to do next?

**Comment by slince** [comment]
Hi:

You should login your qq account  at http://w.qq.com and confirm that you can send and receive message normally.  

if that is ok, exit account from http://w.qq.com. And  retry your code at the CMD.

ps: You are not Chinese?

**Comment by slince** [comment]
hi  you can try new release.  the issue may be fixed according to [#62](https://github.com/ScienJus/smartqq/issues/62)

**Comment by artsemi** [comment]
> ps: You are not Chinese? 
yes ))
But I have Chinese account in http://w.qq.com

I have error 
![image](https://user-images.githubusercontent.com/8996581/36669677-c4fb2eba-1b06-11e8-86da-65ef245aa192.png)

What should I do next? Thanks!

**Comment by slince** [comment]
Hi 
It means that you have to submit your infomration to Tencent and wait for approval， it will take some time.

Ps: This is not a smartqq related issue。。

**Comment by artsemi** [comment]
Thanks for the answer! I'm steel waiting... 7 days
