### ISSUE TITLE
Why don't you teach us how to use 心跳包

### ISSUE THREAD

**Issue by 2488583886** [slince/smartqq#19]
我那个两个小时左右就会断掉，我设置定时器，每15分钟给好友发一次信息，发着发着就没了，该怎么办，求教，qq2488583886，邮箱：2488583886@qq.com

**Comment by slince** [comment]
webqq时基于cookie保存登录状态的，所以长时间没有操作会自动掉线；

你试下用获取在线登录状态 `getFriendsOnlineStatus` 当心跳操作；定制器改短一点，5分钟一次看看；

**Comment by 2488583886** [comment]
我发给你了，最好下午看下，不然晚上可能没空(ノ๑`ȏ´๑)ノ︵⌨

**Comment by slince** [comment]
接口应该返回了100000 code，这个是登录信息失效导致的； 看起来是正常掉线了；

你试下webqq 登进去之后确认可以收发消息之后就不要操作了； 看正常能挂多久会掉线



taosikai@yeah.net
 
发件人： 2488583886
发送时间： 2018-07-24 12:43
收件人： slince/smartqq
抄送： Tao; Comment
主题： Re: [slince/smartqq] Why don't you teach us how to use 心跳包 (#19)
我发给你了，最好下午看下，不然晚上可能没空(ノ๑`ȏ´๑)ノ︵⌨

**Comment by 2488583886** [comment]
我大概修好了，但有了新问题，就是那个获取明信片有问题，获取不全，全名是“【饮冰】明-王阳明”获取的只有【饮冰】明-王“”

**Comment by slince** [comment]
哪个接口

**Comment by 2488583886** [comment]
getGroupDetail

**Comment by 2488583886** [comment]
+getMembers

**Comment by 2488583886** [comment]
+firstByAttribute

**Comment by 2488583886** [comment]
我想问一下，如何查询，信息是否接收完毕，我那个$smartQQ->pollMessages();好像没接收到信息会堵塞

**Comment by slince** [comment]
是的，知道查询到数据才会返回否则会一直卡死在那直到超时错误

**Comment by 2488583886** [comment]
请问下多久超时

**Comment by slince** [comment]
搞不清，挺长的一个时间

**Comment by slince** [comment]
还有问题的话，再打开；我这边先关了
