### ISSUE TITLE
我想给每个用户设置一个qq发送给好友的

### ISSUE THREAD

**Issue by 2488583886** [slince/smartqq#20]
获取二维码的接口不是会堵塞，直到扫描完成吗？那我设置的是在扫描完成后删除二维码，那如果他获取二维码，不去扫描，这样堵塞住了，那就无法执行删除二维码的程序，改怎么办？

**Comment by slince** [comment]
没理解，你要同时登录多个QQ？

**Comment by phpyii** [comment]
查找群报错了

**Comment by slince** [comment]
@phpyii   单开一个issue，吧错误信息贴一下

**Comment by phpyii** [comment]
@slince  不用了，谢谢。找到问题了。我的大号上150个群获取不到，在官网的smartqq上登录也获取不到，小号群少就能获取到

**Comment by phpyii** [comment]
这个问题其实可以关闭了，他问的是生成登录二维码后不去扫码怎么办?
作者代码中已经写了二维码过期后重新生成二维码，当然是一直等待扫码
如果在生成二维码后能加个回调事件就好了，这样就可以自己实现读取二维码图片把二维码显示到控制台了

**Comment by slince** [comment]
是的，二维码过期以后会重新生成；楼上说的事件机制会考虑
