### ISSUE TITLE
我开了三十个那个登录验证的，就一直用swoole异步定时器轮询，报错

### ISSUE THREAD

**Issue by 2488583886** [slince/smartqq#24]
Exception at file[/root/m.lishi/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php] line[113] message:[Client error: `GET https://ssl.ptlogin2.qq.com/ptqrlogin?ptqrtoken=780973688&webqq_type=10&remember_uin=1&login2qq=1&aid=501004106&u1=http%3A%2F%2Fw.qq.com%2Fproxy.html%3Flogin2qq%3D1%26webqq_type%3D10&ptredirect=0&ptlang=2052&daid=164&from_ui=1&pttype=1&dumy=&fp=loginerroralert&action=0-0-4303&mibao_css=m_webqq&t=undefined&g=1&js_type=0&js_ver=10203&login_sig=&pt_randsalt=0` resulted in a `403 Forbidden` response]

**Comment by slince** [comment]
在服务端同一个ip下同时进行三十多个qq登录，腾讯肯定会阻止
