### ISSUE TITLE
执行缓慢怎么破

### ISSUE THREAD

**Issue by 2488583886** [slince/smartqq#25]
$ptWebQQ = $this->getPtWebQQ($this->certificationUrl);
        $vfWebQQ = $this->getVfWebQQ($ptWebQQ);
        list($uin, $pSessionId) = $this->getUinAndPSessionId($ptWebQQ);
        $this->credential = new Credential($ptWebQQ, $vfWebQQ, $pSessionId, $uin, static::$clientId, $this->cookies);
        //获取在线状态避免103
        $this->getFriendsOnlineStatus();
        return $this->credential;
这个要执行好几分钟咋破

**Comment by slince** [comment]
扫码以后，要执行很长时间？
你可以在代码里做几个输出，看看具体是哪一步耗时

**Comment by slince** [comment]
`composer require slince/smartqq  ^2.2@beta`  试试新改版以后的会不会好一点

**Comment by slince** [comment]
有问题的话再开启
