### ISSUE TITLE
detail 404

### ISSUE THREAD

**Issue by caojiabin2012** [slince/smartqq#5]
Fatal error: Uncaught exception 'GuzzleHttp\Exception\ClientException' with message 'Client error: `GET http://s.web2.qq.com/api/get_friend_uin2?tuin=2247542184&type=1&vfwebqq=5c8cf630ac770fbbb8a872eac54a2a0dffb3d4b1c0f0a5bc73a550366297cbf62833df1dcaa8bb51&t=0.1` resulted in a `404 Not Found` response: <html><head><title>Apache Tomcat/7.0.50 - Error report</title><style><!--H1 {font-family:Tahoma,Arial,sans-serif;color:w (truncated...) ' in /mnt/hgfs/htdocs/www/jiabin/demo.jiabin.cn/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:111 Stack trace: #0 /mnt/hgfs/htdocs/www/jiabin/demo.jiabin.cn/vendor/guzzlehttp/guzzle/src/Middleware.php(65): GuzzleHttp\Exception\RequestException::create(Object(GuzzleHttp\Psr7\Request), Object(GuzzleHttp\Psr7\Response)) #1 /mnt/hgfs/htdocs/www/jiabin/demo.jiabin.cn/vendor/guzzlehttp/promises/src/Promise.php(203): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Response)) #2 /mnt/hgfs/htdocs/www/jiabin/demo.jiabin.cn/vendor/guzzlehttp/promises/src/Promise.php(15 in /mnt/hgfs/htdocs/www/jiabin/demo.jiabin.cn/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php on line 111

**Comment by slince** [comment]
OK 我会看一下

**Comment by slince** [comment]
根据报错信息的url来看 你是在尝试获取好友的QQ号并不是好友详情；前者已经被腾讯封了，现在用不了；后者没问题

**Comment by caojiabin2012** [comment]
好




在2017年06月01日 09:55，Tao 写道：

根据报错信息的url来看 你是在尝试获取好友的QQ号并不是好友详情；前者已经被腾讯封了，现在用不了；后者没问题
