### ISSUE TITLE
不能获取消息了

### ISSUE THREAD

**Issue by helloqhq** [slince/smartqq#7]
获取消息接口返回都是这个

> array(3) {
  ["errmsg"]=>
  string(5) "error"
  ["retcode"]=>
  int(0)
  ["retmsg"]=>
  string(2) "ok"
}

**Comment by slince** [comment]
ok，腾讯应该又改规则了，我看下

**Comment by slince** [comment]
已经修复了，直接更新版本2.0.4就好
如果还是有问题，尝试去 [http://w.qq.com/ ](http://w.qq.com/ ) 登录试试能否正常收到消息，如果可以再回过来重试即可。

**Comment by helloqhq** [comment]
运行报错呢

> Parse error: syntax error, unexpected 'class' (T_CLASS), expecting identifier (T_STRING) or variable (T_VARIABLE) or '{' or '$' in /home/helloqhq/smartqq/vendor/slince/smartqq/src/Request/GetGroupsRequest.php on line 56

**Comment by slince** [comment]
php版本和 `/home/helloqhq/smartqq/vendor/slince/smartqq/src/Request/GetGroupsRequest.php` 这个文件内容发一下

**Comment by helloqhq** [comment]
是我php版本过低了，用高版本没问题了
